version: '3.8'
services:
  backend:
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    tty: true
    container_name: ts-backend
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    volumes:
        - "./backend:/ts"
    command: >
        sh -c 'npm start'
  db:
    container_name: db
    build: ./docker/mysql
# windwosの人はplatformの部分を消す
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./docker/.data/log:/var/log/mysqllog"
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot"
        ]
      interval: 5s
      retries: 5